// flow-typed signature: 17c06740f4ba1edeca7fe8c30f9c616c
// flow-typed version: <<STUB>>/@fortawesome/free-solid-svg-icons_v5.9.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/free-solid-svg-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/free-solid-svg-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 **/

declare module '@fortawesome/free-solid-svg-icons/faCheck' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fortawesome/free-solid-svg-icons/faCheck.js' {
  declare module.exports: $Exports<'@fortawesome/free-solid-svg-icons/faCheck'>;
}